name: CD

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set environment for version
        run: long="${{ github.ref }}"; version=${long#"refs/tags/v"}; echo "version=${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - run: brew install libpq
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Publish
        run: ./gradlew -Pversion=$version -Dorg.gradle.parallel=false publish closeAndReleaseStagingRepository
        env:
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SONARTYPE_APIKEY: ${{ secrets.SONARTYPE_APIKEY }}
          SONARTYPE_APITOKEN: ${{ secrets.SONARTYPE_APITOKEN }}
