name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]

    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew
      - run: brew install libpq
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
          gradle-home-cache-cleanup: true
      - run: ./gradlew assemble
      - uses: ikalnytskyi/action-setup-postgres@v4
        with:
          password: password
      - run: ./gradlew build
