name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-14' ]

    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew
      - run: brew install libpq
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit
          gradle-home-cache-cleanup: true
      - run: ./gradlew assemble
      - run: docker-compose --file .devcontainer/docker-compose.yml up -d db
      - run: ./gradlew build
