name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-14', 'macos-latest' ]

    env:
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true

    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew
      - run: brew install libpq
      - uses: ikalnytskyi/action-setup-postgres@v6
        with:
          password: password
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
          gradle-home-cache-cleanup: true
      - run: ./gradlew assemble
      - run: ./gradlew build
