name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew
      - uses: gradle/wrapper-validation-action@v1
      - run: brew install libpq
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew assemble
      - uses: ikalnytskyi/action-setup-postgres@v4
        with:
          password: password
      - run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          path: |
            postgres-native-sqldelight-dialect/build/reports/tests
            postgres-native-sqldelight-driver/build/reports/tests
            testing/build/reports/tests
        if: failure()
